print("Hello, World!")
print("Welcome to Python programming!")
print("Let's start coding!")
print("This is your first Python script.")
print("Enjoy your coding journey!")
print("Happy coding!")
print("Keep practicing and you'll get better!")
print("Python is fun!")
print("You're doing great!")
print("See you next time!")